-- AlterTable
ALTER TABLE `notaFiscal` ADD COLUMN `chave` VARCHAR(191) NOT NULL DEFAULT '',
    ADD COLUMN `protocolo` VARCHAR(191) NOT NULL DEFAULT '',
    ADD COLUMN `status` VARCHAR(191) NOT NULL DEFAULT '',
    ADD COLUMN `url_pdf` VARCHAR(191) NOT NULL DEFAULT '',
    ADD COLUMN `url_xml` VARCHAR(191) NOT NULL DEFAULT '';
